name = "DynamicalSystems"
uuid = "61744808-ddfa-5f27-97ff-6e42cc95d634"
repo = "https://github.com/JuliaDynamics/DynamicalSystems.jl.git"
version = "1.7.1"

[deps]
ChaosTools = "608a59af-f2a3-5ad4-90b4-758bdf3122a7"
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Entropies = "ed8fcbec-b94c-44b6-89df-898894ad9591"
RecurrenceAnalysis = "639c3291-70d9-5ea2-8c5b-839eba1ee399"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ChaosTools = "1.21.1"
DelayEmbeddings = "1.13"
DynamicalSystemsBase = "1.6"
Entropies = "0.11"
RecurrenceAnalysis = "1.3.1"
Reexport = "0.2, 1.0"
StaticArrays = "0.12, 1.0"
julia = "1.5"
