[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ChaosTools = "608a59af-f2a3-5ad4-90b4-758bdf3122a7"
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Entropies = "ed8fcbec-b94c-44b6-89df-898894ad9591"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Neighborhood = "645ca80c-8b79-4109-87ea-e1f58159d116"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecurrenceAnalysis = "639c3291-70d9-5ea2-8c5b-839eba1ee399"
SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
